### ISSUE TITLE
Unable to load "panic: page load error net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by krispayne** [grafana/grafana-kiosk#155]
Starting this morning, I am unable to load my grafana dashboard via the kiosk. I did recently update grafana yesterday, but it worked fine after that. I did notice this morning on my kiosk that raspberry pi OS was asking about labwc, but I got through all of that (at least I think) and am still using X11. 

The URL works fine when I go to it in Chromium via the GUI, and other URLs work when launched via grafana-kiosk. I have no idea what I am doing wrong with this specific URL.

GrafanaKiosk Version: v1.0.7 (same problem on v1.0.8)

Raspberry Pi 4

```
pi@weatherdisplay:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
pi@weatherdisplay:~ $
```

config.yml:
```
general:
  kiosk-mode: full
  autofit: true

target:
  login-method: local
  username: guest
  password: guest
  playlist: false
  URL: http://redacted:3000/d/acf9bcbf-e0be-43bf-a3e2-d02ee9f4182d/tempest-weather-display?orgId=1&from=now-6h&to=now&refresh=10s
```

```
pi@weatherdisplay:~ $ grafana-kiosk -c grafana-kiosk.yml
GrafanaKiosk Version: v1.0.7
2024/11/29 14:34:26 Using config from grafana-kiosk.yml
2024/11/29 14:34:26 AutoFit: true
2024/11/29 14:34:26 LXDEEnabled: false
2024/11/29 14:34:26 LXDEHome: /home/pi
2024/11/29 14:34:26 Mode: full
2024/11/29 14:34:26 WindowPosition: 0,0
2024/11/29 14:34:26 WindowSize:
2024/11/29 14:34:26 ScaleFactor: 1.0
2024/11/29 14:34:26 URL: http://redacted:3000/d/acf9bcbf-e0be-43bf-a3e2-d02ee9f4182d/tempest-weather-display?orgId=1&from=now-6h&to=now&refresh=10s
2024/11/29 14:34:26 LoginMethod: local
2024/11/29 14:34:26 Username: guest
2024/11/29 14:34:26 Password: *redacted*
2024/11/29 14:34:26 IgnoreCertificateErrors: false
2024/11/29 14:34:26 IsPlayList: false
2024/11/29 14:34:26 UseMFA: false
2024/11/29 14:34:26 Fieldname AutoLogin: false
2024/11/29 14:34:26 Fieldname Username:
2024/11/29 14:34:26 Fieldname Password:
2024/11/29 14:34:26 DISPLAY not set, autosetting to :0.0
2024/11/29 14:34:26 DISPLAY= :0.0
2024/11/29 14:34:26 XAUTHORITY not set, autosetting
2024/11/29 14:34:26 XAUTHORITY= /home/pi/.Xauthority
2024/11/29 14:34:26 method  local
2024/11/29 14:34:26 Launching local login kiosk
2024/11/29 14:34:26 Using temp dir: /tmp/chromedp-kiosk3090273426
2024/11/29 14:34:29 KioskMode: Fullscreen
2024/11/29 14:34:29 Navigating to  http://redacted:3000/d/acf9bcbf-e0be-43bf-a3e2-d02ee9f4182d/tempest-weather-display?from=now-6h&kiosk=1&orgId=1&refresh=10s&to=now&autofitpanels
2024/11/29 14:34:29 Sleeping 2000 MS before navigating to url
panic: page load error net::ERR_BLOCKED_BY_CLIENT

goroutine 1 [running]:
github.com/grafana/grafana-kiosk/pkg/kiosk.GrafanaKioskLocal(0x400015de00, 0x400011c360)
        /home/runner/work/grafana-kiosk/grafana-kiosk/pkg/kiosk/local_login.go:79 +0xd30
main.main()
        /home/runner/work/grafana-kiosk/grafana-kiosk/pkg/cmd/grafana-kiosk/main.go:223 +0xa04
pi@weatherdisplay:~ $
```

**Comment by krispayne** [comment]
This appears to be because I'm not running grafana behind https. Any https website I put in my config works fine, it is only http that has an issue.

**Comment by briangann** [comment]
will check for chromedp changes, it should work with both by default.  chromium likely has a new default that needs to be overridden.

**Comment by pconwell** [comment]
@briangann for what it's worth, I spent a while trying to dig into this today but didn't make any real progress.

The closest issue I found that seems to be in the same family of problems is this: https://github.com/chromedp/chromedp/issues/1525. It may not be related at all, but almost everything else I found related to `ERR_BLOCKED_BY_CLIENT` involved having an ad blocker installed - which does not apply here.

**Comment by briangann** [comment]
still chasing this one, it doesn't do this on chromium on darwin, but will try with a pi.

**Comment by dresco** [comment]
Just +1 on this, updated packages on my Raspian bookworm install & ran into this same issue today.
Downgrading chromium has fixed it for now...

**Comment by pconwell** [comment]
Just to follow up on my end - I ended up having our IT department set up an https virtual IP to wrap the http endpoint and was able to work around the issue that way. Doesn't fix the issue, but I wanted to provide a follow up on where I'm at.

**Comment by briangann** [comment]
Can you try with version 1.0.9?  I'm still not getting a repro on this.

**Comment by briangann** [comment]
didn't mean to close this!

**Comment by dresco** [comment]
> Can you try with version 1.0.9? I'm still not getting a repro on this.

Can confirm I was testing with latest 1.09 binary from the assets page.

I'd just done a `sudo apt update && sudo apt full-upgrade` on the Pi running Raspberry Pi OS / Raspian Bookworm, which bumped chromium up to version 130 (sorry, didn't keep a note of the previous version).

Happy to try what I can to troubleshoot..

**Comment by pconwell** [comment]
Sorry for the super delayed follow-up. I'm still seeing the same issue on 1.0.9.

If I use https, it seems to be fine - but if I use http, it goes into a restart loop.

I don't know exactly what I'm looking for, but it appears the error is around here in the syslog:

```
2025-06-27T14:52:16.783608-05:00 grafana-4 grafana-kiosk[7088]: #011/home/runner/work/grafana-kiosk/grafana-kiosk/pkg/cmd/grafana-kiosk/main.go:244 +0xa78
2025-06-27T14:52:16.786495-05:00 grafana-4 systemd[1]: grafana-kiosk.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
2025-06-27T14:52:16.786830-05:00 grafana-4 systemd[1]: grafana-kiosk.service: Failed with result 'exit-code'.
```

**Comment by briangann** [comment]
Opened PR #249 with a fix for this.

**Root cause:** Chromium 130+ enables HTTPS-First Mode (`HttpsUpgrades` feature) by default. When navigating to an HTTP URL, Chromium tries to upgrade it to HTTPS. If the HTTPS connection fails (as it will for a local Grafana instance not running TLS), Chromium blocks the request with `ERR_BLOCKED_BY_CLIENT`.

**Fix:** Add `HttpsUpgrades` to the `--disable-features` Chrome flag so grafana-kiosk disables HTTPS-First Mode, restoring pre-130 behavior for plain HTTP URLs.

Would appreciate if anyone affected can test the fix — you can build from the PR branch or wait for the next release.
