### ISSUE TITLE
Windows timeout to websocket Chrome to short

### ISSUE THREAD

**Issue by BasvanH** [grafana/grafana-kiosk#43]
Hello,

We are using rather slow Celeron Intel nucs for our Grafana screens. Sometimes, the startup is to slow and grafana-kiosk stops with an error. It would be great if this timeout could be extended or settable.

```
C:\xxxx\GrafanaKiosk>C:\xxxx\GrafanaKiosk\grafana-kiosk.windows.amd64.exe -c C:\xxxx\GrafanaKiosk\config.yaml
2020/08/24 10:18:40 Using config from C:\temp\GrafanaKiosk\config.yaml
2020/08/24 10:18:41 AutoFit: true
2020/08/24 10:18:41 LXDEEnabled: false
2020/08/24 10:18:41 LXDEHome: /home/pi
2020/08/24 10:18:41 Mode: full
2020/08/24 10:18:41 URL: https://grafana.xxxx.xxxx/playlists/play/9?kiosk
2020/08/24 10:18:41 LoginMethod: local
2020/08/24 10:18:41 Username: xxxx
2020/08/24 10:18:41 Password: *redacted*
2020/08/24 10:18:41 IgnoreCertificateErrors: false
2020/08/24 10:18:41 IsPlayList: true
2020/08/24 10:18:41 AutoFit: true
2020/08/24 10:18:41 LXDEEnabled: false
2020/08/24 10:18:41 LXDEHome: /home/pi
2020/08/24 10:18:41 Mode: full
2020/08/24 10:18:41 URL: https://grafana.xxxx.xxxx/playlists/play/9?kiosk
2020/08/24 10:18:41 LoginMethod: local
2020/08/24 10:18:41 Username: xxxx
2020/08/24 10:18:41 Password: *redacted*
2020/08/24 10:18:41 IgnoreCertificateErrors: false
2020/08/24 10:18:41 IsPlayList: true
2020/08/24 10:18:41 DISPLAY not set, autosetting to :0.0
2020/08/24 10:18:41 DISPLAY= :0.0
2020/08/24 10:18:41 XAUTHORITY not set, autosetting
2020/08/24 10:18:41 XAUTHORITY= /.Xauthority
2020/08/24 10:18:41 method  local
2020/08/24 10:18:41 Launching local login kiosk
panic: websocket url timeout reached

goroutine 1 [running]:
github.com/grafana/grafana-kiosk/pkg/kiosk.GrafanaKioskLocal(0xc0000c3490)
        /go/src/github.com/grafana/grafana-kiosk/pkg/kiosk/local_login.go:49 +0xc24
main.main()
        /go/src/github.com/grafana/grafana-kiosk/pkg/cmd/grafana-kiosk/main.go:153 +0x35e
```

Kind regards,
Bastiaan van Haastrecht

**Comment by kskenyon** [comment]
Having the same problem on a slow pi.  Any way to fix it?

**Comment by BasvanH** [comment]
We applied a work-around by delay starting the kiosk. But this requires a settable option to fit all needs.

**Comment by fechnert** [comment]
Had this problem too. For me it was solved by installing `rng-tools` via `apt install rng-tools`.

chromium-browser took ages to load after upgrading to the latest version because the random module was missing entropy. it blocked to start chromium until enough entropy was generated.

By installing the mentioned package, this was solved.

Some references:

- https://unix.stackexchange.com/a/493251
- https://www.raspberrypi.org/forums/viewtopic.php?t=237147
