### ISSUE TITLE
Chromium update issue, can I use another browser?

### ISSUE THREAD

**Issue by Onc3k** [grafana/grafana-kiosk#50]
Hello,

the grafana-kiosk doesn't work with a newer version of chromium then  78.0.xxx, maybe someone have a solution?

Is possible to use some another browser? If yes, please how I can change it? 

Many thanks.

**Comment by briangann** [comment]
what error are you seeing?

**Comment by Onc3k** [comment]
There is not any specific error, I see just "Command finished with error: exit status 1". Maybe I can start some debug mode? But there https://www.raspberrypi.org/forums/viewtopic.php?t=272394 I read that Chromium V78 is latest supported via Raspberry Pi HW. When is chromium updated from v78, I see instead of my Grafana dashboard only white page.

**Comment by briangann** [comment]
i'm not seeing this problem on my pi3, with these packages, are you still seeing this?

```
ii  chromium-browser                     88.0.4324.187-rpt1                      armhf        Chromium web browser, open-source version of Chrome
ii  chromium-browser-l10n                88.0.4324.187-rpt1                      all          chromium-browser language packages
ii  chromium-codecs-ffmpeg-extra         88.0.4324.187-rpt1                      armhf        Extra ffmpeg codecs for the Chromium Browser
```

**Comment by Onc3k** [comment]
> i'm not seeing this problem on my pi3, with these packages, are you still seeing this?
> 
> ```
> ii  chromium-browser                     88.0.4324.187-rpt1                      armhf        Chromium web browser, open-source version of Chrome
> ii  chromium-browser-l10n                88.0.4324.187-rpt1                      all          chromium-browser language packages
> ii  chromium-codecs-ffmpeg-extra         88.0.4324.187-rpt1                      armhf        Extra ffmpeg codecs for the Chromium Browser
> ```

Hello,

with these packages it doesn't works. I tryed to use latest version of kiosk 1.0.4 for armv7 and still same result (only white page). After revert back chromium to version **"Chromium 78.0.3904.108 Built on Raspbian , running on Raspbian 10"** by using https://github.com/Botspot/chromium78 it's working again.

Used system etc.:

> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

> 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

Used settings:

> general:
  kiosk-mode: full
  autofit: true
  lxde: true
  lxde-home: /home/pi

> target:
>   login-method: local
>   username: xxxx
>   password: xxxx
>   playlist: true
>   #URL: https://linktoplaylist
>   URL: https://linktoplaylist
>   ignore-certificate-errors: true

systemd daemon settings:

> [Unit]
> Description=Start Grafana
> #Requires=graphical.target
> #After=graphical.target
> 
> [Service]
> Environment=DISPLAY=:0
> Environment=XAUTHORITY=/home/pi/.Xauthority
> ExecStart=/usr/bin/grafana-kioskk -c /etc/grafana-kiosk/config.yaml
> Restart=always
> RestartSec=10s
> KillMode=process
> TimeoutSec=infinity
> 
> [Install]
> WantedBy=graphical.target

**Comment by GeekyTim** [comment]
I've just updated my Pi (usually one on a weekly basis) and the Kiosk no longer works. I get the following:

-- Logs begin at Sun 2022-01-30 21:26:37 GMT, end at Sun 2022-01-30 21:50:10 GMT. --
Jan 30 21:26:53 KioskPi2 systemd[1]: Started Grafana Kiosk.
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 No config specified, using environment and args
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 AutoFit: true
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 LXDEEnabled: true
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 LXDEHome: /home/pi
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 Mode: full
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 URL: http://picm3-2.localdomain:3000/playlists/play/1?kiosk&autofitpanels&kiosk
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 LoginMethod: local
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 Username: geekytim
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 Password: *redacted*
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 IgnoreCertificateErrors: false
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 IsPlayList: true
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 AutoFit: true
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 LXDEEnabled: true
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 LXDEHome: /home/pi
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 Mode: full
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 URL: http://picm3-2.localdomain:3000/playlists/play/1?kiosk&autofitpanels&kiosk
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 LoginMethod: local
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 Username: geekytim
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 Password: *redacted*
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 IgnoreCertificateErrors: false
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 IsPlayList: true
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 path: /home/pi
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 command: /usr/bin/lxpanel
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 arg0: --profile
Jan 30 21:26:53 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:53 Waiting for command to finish...
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Command finished with error: exit status 1
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 path: /home/pi
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 command: /usr/bin/pcmanfm
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 arg0: --desktop
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Waiting for command to finish...
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Command finished with error: exit status 1
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 path: /home/pi
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 command: /usr/bin/xset
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 arg0: --desktop
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Waiting for command to finish...
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Command finished with error: exit status 1
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 path: /home/pi
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 command: /usr/bin/xset
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 arg0: s
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Waiting for command to finish...
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Command finished with error: exit status 1
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 path: /home/pi
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 command: /usr/bin/xset
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 arg0: -dpms
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Waiting for command to finish...
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Command finished with error: exit status 1
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 path: /home/pi
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 command: /usr/bin/xset
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 arg0: s
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Waiting for command to finish...
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Command finished with error: exit status 1
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 DISPLAY= :0
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 XAUTHORITY= /home/pi/.Xauthority
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 method  local
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Launching local login kiosk
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 path: /home/pi
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 command: /usr/bin/unclutter
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 arg0: -display
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Waiting for command to finish...
Jan 30 21:26:54 KioskPi2 grafana-kiosk[423]: 2022/01/30 21:26:54 Command finished with error: exit status 1
Jan 30 21:27:03 KioskPi2 grafana-kiosk[423]: panic: chrome failed to start:
Jan 30 21:27:03 KioskPi2 grafana-kiosk[423]: BlueALSA detected - Disabling audio sandbox
Jan 30 21:27:03 KioskPi2 grafana-kiosk[423]: Invalid MIT-MAGIC-COOKIE-1 key[0130/212703.605508:ERROR:elf_dynamic_array_reader.h(61)] tag not found
Jan 30 21:27:03 KioskPi2 grafana-kiosk[423]: goroutine 1 [running]:
Jan 30 21:27:03 KioskPi2 grafana-kiosk[423]: github.com/grafana/grafana-kiosk/pkg/kiosk.GrafanaKioskLocal(0x19504c0)
Jan 30 21:27:03 KioskPi2 grafana-kiosk[423]:         /go/src/github.com/grafana/grafana-kiosk/pkg/kiosk/local_login.go:49 +0x97c
Jan 30 21:27:03 KioskPi2 grafana-kiosk[423]: main.main()
Jan 30 21:27:03 KioskPi2 grafana-kiosk[423]:         /go/src/github.com/grafana/grafana-kiosk/pkg/cmd/grafana-kiosk/main.go:153 +0x2bc
Jan 30 21:27:03 KioskPi2 systemd[1]: grafana-kiosk.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 30 21:27:03 KioskPi2 systemd[1]: grafana-kiosk.service: Failed with result 'exit-code'.

Is there a solution, please?

**Comment by briangann** [comment]
i'm not seeing this on any of my installs, are you still seeing it?
