### ISSUE TITLE
V1.0.3 fail to start

### ISSUE THREAD

**Issue by thib3113** [grafana/grafana-kiosk#57]
I'm running grafana-kiosk on a Raspberry pi 4 . 

Running the tool will produce this error : 
```
root@agent:/home/thib3113# ./grafana-kiosk.linux.armv6 -c /home/pi/grafana/config.yml
2021/06/29 11:18:07 Using config from /home/pi/grafana/config.yml
2021/06/29 11:18:07 AutoFit: true
2021/06/29 11:18:07 LXDEEnabled: false
2021/06/29 11:18:07 LXDEHome: /home/pi
2021/06/29 11:18:07 Mode: disabled
2021/06/29 11:18:07 WindowPosition: 0,0
2021/06/29 11:18:07 URL: https://********/playlists/play/1
2021/06/29 11:18:07 LoginMethod: local
2021/06/29 11:18:07 Username: **********
2021/06/29 11:18:07 Password: **********
2021/06/29 11:18:07 IgnoreCertificateErrors: false
2021/06/29 11:18:07 IsPlayList: true
2021/06/29 11:18:07 Fieldname Username: false
2021/06/29 11:18:07 Fieldname Username:
2021/06/29 11:18:07 Fieldname Password:
2021/06/29 11:18:07 AutoFit: true
2021/06/29 11:18:07 LXDEEnabled: false
2021/06/29 11:18:07 LXDEHome: /home/pi
2021/06/29 11:18:07 Mode: disabled
2021/06/29 11:18:07 WindowPosition: 0,0
2021/06/29 11:18:07 URL: https://********/playlists/play/1
2021/06/29 11:18:07 LoginMethod: local
2021/06/29 11:18:07 Username: raspberrypi
2021/06/29 11:18:07 Password: *redacted*
2021/06/29 11:18:07 IgnoreCertificateErrors: false
2021/06/29 11:18:07 IsPlayList: true
2021/06/29 11:18:07 Fieldname Username: false
2021/06/29 11:18:07 Fieldname Username:
2021/06/29 11:18:07 Fieldname Password:
2021/06/29 11:18:07 DISPLAY not set, autosetting to :0.0
2021/06/29 11:18:07 DISPLAY= :0.0
2021/06/29 11:18:07 XAUTHORITY not set, autosetting
2021/06/29 11:18:07 XAUTHORITY= /root/.Xauthority
2021/06/29 11:18:07 method  local
2021/06/29 11:18:07 Launching local login kiosk
panic: invalid exec pool flag

goroutine 1 [running]:
github.com/grafana/grafana-kiosk/pkg/kiosk.GrafanaKioskLocal(0x15226c0)
        /go/src/github.com/grafana/grafana-kiosk/pkg/kiosk/local_login.go:50 +0x9cc
main.main()
        /go/src/github.com/grafana/grafana-kiosk/pkg/cmd/grafana-kiosk/main.go:171 +0x2c8
```

I'm using the same configuration for the 1.0.2 and it works ( I tryed .armv6 / armv7 and same error )

**Comment by briangann** [comment]
will have a fix shortly, one of the new flags is being interpreted incorrectly.

**Comment by briangann** [comment]
just release v1.0.4, please give that a try, it's working on my devices here.

**Comment by RyuunosukeDS3** [comment]
Trying it right now (had the same error)

**Comment by RyuunosukeDS3** [comment]
```grafana-kiosk -URL=http://myip:3000/ -login-method=local -username=myuser -password=mypass-window-position="900,500"
2021/06/29 16:34:33 No config specified, using environment and args
2021/06/29 16:34:33 AutoFit: true
2021/06/29 16:34:33 LXDEEnabled: false
2021/06/29 16:34:33 LXDEHome: /home/pi
2021/06/29 16:34:33 Mode: full
2021/06/29 16:34:33 WindowPosition: 900,500
2021/06/29 16:34:33 URL: http://172.30.0.5:3000/
2021/06/29 16:34:33 LoginMethod: local
2021/06/29 16:34:33 Username: myuser
2021/06/29 16:34:33 Password: *redacted*
2021/06/29 16:34:33 IgnoreCertificateErrors: false
2021/06/29 16:34:33 IsPlayList: false
2021/06/29 16:34:33 Fieldname Username: false
2021/06/29 16:34:33 Fieldname Username: username
2021/06/29 16:34:33 Fieldname Password: password
2021/06/29 16:34:33 AutoFit: true
2021/06/29 16:34:33 LXDEEnabled: false
2021/06/29 16:34:33 LXDEHome: /home/pi
2021/06/29 16:34:33 Mode: full
2021/06/29 16:34:33 WindowPosition: 900,500
2021/06/29 16:34:33 URL: http://myip:3000/
2021/06/29 16:34:33 LoginMethod: local
2021/06/29 16:34:33 Username: myuser
2021/06/29 16:34:33 Password: *redacted*
2021/06/29 16:34:33 IgnoreCertificateErrors: false
2021/06/29 16:34:33 IsPlayList: false
2021/06/29 16:34:33 Fieldname Username: false
2021/06/29 16:34:33 Fieldname Username: username
2021/06/29 16:34:33 Fieldname Password: password
2021/06/29 16:34:33 DISPLAY= :0
2021/06/29 16:34:33 XAUTHORITY= /run/user/1000/gdm/Xauthority
2021/06/29 16:34:33 method  local
2021/06/29 16:34:33 Launching local login kiosk
2021/06/29 16:34:44 KioskMode: Fullscreen
2021/06/29 16:34:44 Navigating to  http://172.30.0.5:3000/?kiosk=1&autofitpanels
panic: context canceled

goroutine 1 [running]:
github.com/grafana/grafana-kiosk/pkg/kiosk.GrafanaKioskLocal(0xc0000fa2c0)
	/go/src/github.com/grafana/grafana-kiosk/pkg/kiosk/local_login.go:71 +0xcb7
main.main()
	/go/src/github.com/grafana/grafana-kiosk/pkg/cmd/grafana-kiosk/main.go:171 +0x377
```

It opens, but "-window-position" did not work

**Comment by briangann** [comment]
i'm not seeing this on darwin (able to startup on different displays), i won't have a dual display pi4 until later this week.

**Comment by RyuunosukeDS3** [comment]
Will test some more tomorrow on the actual RPI4, could you share your command line/config file? just so i can check if i'm doing it correctly?

**Comment by RyuunosukeDS3** [comment]
> i'm not seeing this on darwin (able to startup on different displays), i won't have a dual display pi4 until later this week.
> 
> are you testing on linux amd64 or windows?

Linux. Sorry!

**Comment by briangann** [comment]
this opens the kiosk on my right display `./bin/grafana-kiosk.darwin -window-position=3009,0`
i'm running scaled on both displays at 3008x1692

i'll switch over to linux and see what it does.

**Comment by thib3113** [comment]
works for me :) .

**Comment by briangann** [comment]
just tried - worked on ubuntu 20.04 LTS with dual displays, `grafana-kiosk.linux.amd64 -window-position=3009,0`

**Comment by RyuunosukeDS3** [comment]
Could it be, because I was running it on a VM? It shoukd work on the RPI4. Will be trying it tomorrow. Thanks!

**Comment by briangann** [comment]
> Could it be, because I was running it on a VM? It shoukd work on the RPI4. Will be trying it tomorrow. Thanks!

i haven't tried it on a VM, the display output might be different.
